export {default as  About} from './About'
export {default as  Error} from './Error'
export {default as  Cocktail} from './Cocktail'
export {default as  Homelayout} from './Homelayout'
export {default as  Landing} from './Landing'
export {default as  Newsletter} from './Newsletter'
export {default as CocktailDetails} from './CocktailDetails'
